name: 'PDK Release'
description: 'Github Action for pdk release'
inputs:
  release-action:
    description: 'What pdk release action to use'
    required: true
    default: 'prep'
  validate-ignore:
    description: |
      A comma-separated list of paths that will be added
      to the PDK config 'project.validate.ignore'. These
      paths can use wildcard patterns with the same syntax
      as a .gitignore entry. All paths are relative to the
      module directory.
    required: false
    default: 'spec/**/*'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release-action }}
    - ${{ inputs.validate-ignore }}
